version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gameoflife_postgres
    environment:
      POSTGRES_DB: gameoflife
      POSTGRES_USER: gameoflife_user
      POSTGRES_PASSWORD: gameoflife_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameoflife_user -d gameoflife"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__GameOfLifeDatabase=Server=postgres;Database=gameoflife;User Id=gameoflife_user;Password=gameoflife_password;
    restart: on-failure

volumes:
  postgres_data:
    name: gameoflife_postgres_data
